@ScheduleApi_HostAddress = http://localhost:32770

GET {{ScheduleApi_HostAddress}}/api/week/
Accept: application/json

###

GET {{ScheduleApi_HostAddress}}/api/groups/
Accept: application/json

###

GET {{ScheduleApi_HostAddress}}/api/professors/
Accept: application/json

###

GET {{ScheduleApi_HostAddress}}/api/groupsandprofessors/
Accept: application/json

###

GET {{ScheduleApi_HostAddress}}/api/schedule/9791
Accept: application/json

###

GET http://95.164.92.97:8080/api/groupsandprofessors
Accept: application/json

###